version: "3.7"

services:
  permission_db:
    image: mariadb:10.5.6
    container_name: permission_db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./.dockerfile/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - permission-network

  permission_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: permission_phpmyadmin
    depends_on:
      - permission_db
    environment:
      PMA_HOST: permission_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8888:80
    networks:
      - permission-network

  permission-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: permission
        uid: 1000
    image: 'permission-app'
    container_name: 'permission-app'
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./.dockerfile/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - permission-network

  permission-webserver:
    image: nginx:alpine
    container_name: 'permission-webserver'
    restart: unless-stopped
    tty: true
    ports:
      - "8100:80"
      - "8143:443"
    volumes:
      - ./:/var/www
      - ./.dockerfile/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - permission-network

volumes:
  mariadbdata:

networks:
  permission-network:
    driver: bridge
